### ISSUE TITLE
OS X 10.10 Compile fails in stage 3

### ISSUE THREAD

**Issue by ysgard** [alvatar/sphere-core#16]
This is with the latest version of gambit.  I tried this with both the release and development versions of sphere-core.  Happens during the sudo ./bootstrap
...
Do you want to compile the syntax expander? Yes/No
Yes
**\* INFO -- Compiling syntax-case expander...
**\* ERROR -- Can't find file "/Users/ysgard/sphere-core/src/scsc/syntax-case.scm"
**\* INFO -- finished task compile-stage-2
**\* INFO -- running task post-compile-stage-2
**\* INFO -- deleting /usr/local/Gambit-C/spheres/spheres.scm
**\* INFO -- copying /Users/ysgard/sphere-core/src/spheres.scm to ~~spheres/spheres.scm
**\* INFO -- Installing macro expander
**\* ERROR IN sake#directory?, "src/sake/filesets.scm"@85.8 -- No such file or directory
(file-type "/Users/ysgard/sphere-core/src/scsc/syntax-case.scm")
**\* INFO -- entering directory /Users/ysgard/sphere-core/
**\* INFO -- Bootstrapping: syntax expander omitted
**\* INFO -- running task compile-stage-3
**\* INFO -- compiling module to C -- core: base version: (debug)
**\* INFO -- Bootstrapping: syntax expander omitted
**\* ERROR IN (string)@1.56 -- Ill-formed expression
**\* ERROR -- error compiling generated C file
**\* ERROR -- sake error, aborting

**Comment by alvatar** [comment]
How did you reach this version?
Sphere-core is deprecated. The version that I´m supporting at the moment is https://github.com/fourthbit/spheres
Please, install that version!

**Comment by ysgard** [comment]
I got it from here: http://www.schemespheres.org/guides/en/quickstart

I should have paid more heed to the header, I just noticed the update notice now.  My bad, I'll try the updated version.

**Comment by alvatar** [comment]
I have to update all that documentation! ;)
